package GUI;

import civitas.TituloPropiedad;

public class PropiedadPanel extends javax.swing.JPanel {

    TituloPropiedad tituloPropiedad;
    
    public PropiedadPanel() {
        initComponents();
    }

    void setPropiedad(TituloPropiedad t){
        tituloPropiedad = t;
        field_nombre.setText(tituloPropiedad.getNombre());
        field_numcasas.setText(Float.toString(tituloPropiedad.getNumCasas()));
        field_numhoteles.setText(Float.toString(tituloPropiedad.getNumHoteles()));
        field_hipotecada.setText(Boolean.toString(tituloPropiedad.getHipotecado()));
    
        field_nombre.repaint();
        field_numcasas.repaint();
        field_numhoteles.repaint();
        field_hipotecada.repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_nombre = new javax.swing.JLabel();
        label_numcasas = new javax.swing.JLabel();
        label_numhoteles = new javax.swing.JLabel();
        label_hipotecada = new javax.swing.JLabel();
        field_nombre = new javax.swing.JTextField();
        field_numcasas = new javax.swing.JTextField();
        field_numhoteles = new javax.swing.JTextField();
        field_hipotecada = new javax.swing.JTextField();

        label_nombre.setText("Nombre:");
        label_nombre.setEnabled(false);

        label_numcasas.setText("Num. Casas:");
        label_numcasas.setEnabled(false);

        label_numhoteles.setText("Num. Hoteles:");
        label_numhoteles.setEnabled(false);

        label_hipotecada.setText("Hipotecada:");
        label_hipotecada.setEnabled(false);

        field_nombre.setText("jTextField1");
        field_nombre.setEnabled(false);

        field_numcasas.setText("jTextField2");
        field_numcasas.setEnabled(false);

        field_numhoteles.setText("jTextField3");
        field_numhoteles.setEnabled(false);
        field_numhoteles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_numhotelesActionPerformed(evt);
            }
        });

        field_hipotecada.setText("jTextField4");
        field_hipotecada.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_hipotecada)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(field_hipotecada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_nombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(field_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_numcasas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(field_numcasas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_numhoteles)
                        .addGap(18, 18, 18)
                        .addComponent(field_numhoteles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_nombre)
                    .addComponent(field_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_numcasas)
                    .addComponent(field_numcasas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_numhoteles)
                    .addComponent(field_numhoteles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_hipotecada)
                    .addComponent(field_hipotecada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void field_numhotelesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_numhotelesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_numhotelesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField field_hipotecada;
    private javax.swing.JTextField field_nombre;
    private javax.swing.JTextField field_numcasas;
    private javax.swing.JTextField field_numhoteles;
    private javax.swing.JLabel label_hipotecada;
    private javax.swing.JLabel label_nombre;
    private javax.swing.JLabel label_numcasas;
    private javax.swing.JLabel label_numhoteles;
    // End of variables declaration//GEN-END:variables
}
